# Generated by Django 3.2.13 on 2022-05-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
