# Generated by Django 3.2.13 on 2022-05-24 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
        ('journeys', '0002_delete_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Suspended'), (-1, 'Deleted')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='passengers.passenger')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
            },
        ),
    ]
