# Generated by Django 3.2.13 on 2022-05-25 18:05

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), geography=True, null=True, srid=4326),
        ),
    ]
