# Generated by Django 3.2.13 on 2022-05-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_auto_20220525_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='price',
        ),
    ]
